// Navigate to the time-picking place and run:
/* 
  [...document.querySelectorAll('select[name=SectionId] > option')].map(o => ({sectionId: Number(o.value), name: o.textContent.trim()})).reduce((res, o) => ({...res, [o.sectionId]: o.name}), {})
*/
const stations = {
  blekinge:{
    0: "Alla expeditioner",
    105: "Karlskrona",
    106: "Karlshamn",
  },
  dalarna:{
    0: "Alla expeditioner",
    6: "Borlänge",
    50: "Avesta",
    55: "Ludvika",
    56: "Mora",
  },
  gotland:{
    0: "Välj i listan",
    12: "Visby",
  },
  gavleborg: {
    0: "Alla expeditioner",
    13: "Gävle",
    32: "Hudiksvall",
    37: "Bollnäs",
  },
  halland:{
    0: "Alla expeditioner",
    94: "Kungsbacka",
    95: "Varberg",
    96: "Falkenberg",
    97: "Halmstad",
  },
  jamtland:{
    0: "Alla expeditioner",
    9: "Östersund",
    62: "Funäsdalen",
    73: "Strömsund",
    74: "Sveg",
    77: "Åre",
  },
  jonkoping: {
    0: "Alla expeditioner",
    82: "Eksjö",
    83: "Jönköping",
    84: "Värnamo",
  },
  kalmar: {
    0: "Alla expeditioner",
    102: "Kalmar",
    103: "Oskarshamn",
    104: "Västervik",
  },
  kronoberg: {
    0: "Alla expeditioner",
    98: "Ljungby",
    99: "Växjö",
    100: "Älmhult",
  },
  norrbotten: {
    0: "Alla expeditioner",
    60: "Arvidsjaur",
    61: "Boden",
    63: "Gällivare",
    64: "Haparanda",
    65: "Kalix",
    66: "Kiruna",
    70: "Piteå",
    79: "Luleå",
  },
  skane: {
    0: "Alla expeditioner",
    67: "Klippan",
    108: "Hässleholm",
    109: "Kristianstad",
    110: "Eslöv",
    111: "Helsingborg",
    112: "Malmö",
    114: "Landskrona",
    115: "Ängelholm",
    116: "Trelleborg",
    117: "Ystad",
    118: "Lund",
  },
  sodermanland:{
    0: "Alla expeditioner",
    85: "Eskilstuna",
    86: "Katrineholm",
    87: "Nyköping",
    88: "Skavsta",
    89: "Strängnäs",
  },
  stockholm: {
    0: "Alla expeditioner",
    38: "Flemingsberg",
    40: "Globen",
    41: "Sthlm City",
    42: "Solna",
    43: "Sollentuna",
    44: "Norrtälje",
    45: "Nacka",
    46: "Haninge",
    47: "Södertälje",
    48: "Södra Roslagen (Täby)",
    113: "Järva (Rinkeby)",
  },
  uppsala: {
    0: "Alla expeditioner",
    3: "Enköping",
    5: "Uppsala",
    33: "Östhammar",
    34: "Tierp",
  },
  varmland:{
    0: "Alla expeditioner",
    7: "Karlstad",
    49: "Arvika",
    53: "Kristinehamn",
    57: "Torsby",
  },
  vasterbotten: {
    0: "Alla expeditioner",
    11: "Skellefteå",
    69: "Lycksele",
    72: "Storuman",
    75: "Vilhelmina",
    81: "Umeå",
  },
  vasternorrland: {
    0: "Alla expeditioner",
    10: "Härnösand",
    68: "Kramfors",
    71: "Sollefteå",
    76: "Ånge",
    78: "Örnsköldsvik",
    80: "Sundsvall",
  },
  vastmanland: {
    0: "Alla expeditioner",
    2: "Köping",
    35: "Sala",
    36: "Fagersta",
    93: "Västerås",
  },
  vastragotaland: {
    0: "Alla expeditioner",
    15: "Göteborg",
    16: "Mölndal",
    17: "Alingsås",
    18: "Borås",
    19: "Mark/Kinna",
    20: "Ulricehamn",
    23: "Åmål",
    24: "Falköping",
    25: "Uddevalla",
    26: "Mariestad",
    27: "Skövde",
    28: "Stenungsund",
    29: "Strömstad",
    30: "Trollhättan",
    31: "Lidköping",
  },
  orebro: {
    0: "Alla expeditioner",
    8: "Örebro",
    51: "Hallsberg",
    52: "Karlskoga",
    54: "Lindesberg",
    58: "Vivalla",
  },
  ostergotland:{
    0: "Alla expeditioner",
    90: "Linköping",
    91: "Motala",
    92: "Norrköping",
  }
}